name: ModPlugin
version: 1.0
author: Redwoub
main: fr.redwoub.modplugin.Main
commands:
  check:
    permission-message: §cYou don't have permission
    permission: mod.use
  discord:
  vanish:
    permission: mod.use
    permission-message: §cYou don't have permission